config/routes.rb
Toys4u::Application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :toys

  root :to => 'store#index', :as => 'store'
  

end

app/models/toy.rb
class Toy < ActiveRecord::Base
  default_scope :order => 'title'

  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true
  # validates :image_url, :format => {
  #   :with    => %r{\.(gif|jpg|png)$}i,
  #   :message => 'must be a URL for GIF, JPG or PNG image.'
  # 	:multiline => true
  # }
  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :set_toy, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_admin!
    
  # GET /toys
  # GET /toys.json
  def index
    @toys = Toy.all
  end

  # GET /toys/1
  # GET /toys/1.json
  def show
  end

  # GET /toys/new
  def new
    @toy = Toy.new
  end

  # GET /toys/1/edit
  def edit
  end

  # POST /toys
  # POST /toys.json
  def create
    @toy = Toy.new(toy_params)

    respond_to do |format|
      if @toy.save
        format.html { redirect_to @toy, notice: 'Toy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @toy }
      else
        format.html { render action: 'new' }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toys/1
  # PATCH/PUT /toys/1.json
  def update
    respond_to do |format|
      if @toy.update(toy_params)
        format.html { redirect_to @toy, notice: 'Toy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @toy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toys/1
  # DELETE /toys/1.json
  def destroy
    @toy.destroy
    respond_to do |format|
      format.html { redirect_to toys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_toy
      @toy = Toy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def toy_params
      params.require(:toy).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/views/toys/_form.html.erb
<%= form_for(@toy) do |f| %>
  <% if @toy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@toy.errors.count, "error") %> prohibited this toy from being saved:</h2>

      <ul>
      <% @toy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/toys/edit.html.erb
<h1>Editing toy</h1>

<%= render 'form' %>

<%= link_to 'Show', @toy %> |
<%= link_to 'Back', toys_path %>

app/views/toys/index.html.erb
<div id="toys_list" >
  <h1>Listing toys</h1>

  <table>
    <% @toys.each do |toy| %>
      <tr class=" <%= cycle('list_line_odd' , 'list_line_even' ) %>" >
        <td>
         <%= image_tag(toy.image_url, :class => 'list_image', :width => 300 ) %>
        </td>
        <td class="list_description" >
          <dl>
            <dt><%= toy.title %></dt>
            <dd><%= truncate(strip_tags(toy.description), :length => 80) %></dd>
          </dl>
        </td>
        <td class="list_actions" >
          <%= link_to 'Show' , toy %><br/>
          <%= link_to 'Edit' , edit_toy_path(toy) %><br/>
          <%= link_to 'Destroy' , toy, :confirm => 'Are you sure?' , :method => :delete %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<br />
<%= link_to 'New toy' , new_toy_path %>

app/views/toys/new.html.erb
<h1>New toy</h1>

<%= render 'form' %>

<%= link_to 'Back', toys_path %>

app/views/toys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @toy.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @toy.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @toy.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @toy.price %>
</p>

<%= link_to 'Edit', edit_toy_path(@toy) %> |
<%= link_to 'Back', toys_path %>